version: '3.5'

services:
  backend:
    container_name: digit_backend
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/home/node
      - /home/node/node_modules
    ports:
      - '3001:3001'
      - '9230:9230'
    depends_on:
      - db
    entrypoint: pm2-runtime
    command: ['digit_dev.config.js']
  db:
    image: postgres
    container_name: digit_db
    restart: always
    environment:
      POSTGRES_USER: digit
      POSTGRES_PASSWORD: digit
      POSTGRES_DB: digit_dev
    ports:
      - '5432:5432'