version: 2
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: cimg/node:15.8.0
    steps: 
      - checkout
      - setup_remote_docker
      - run:
          name: Test with docker-compose
          command: docker-compose -f docker-compose-test.yaml run --rm backendtest npm test
  deploy:
    working_directory: ~/tmp
    docker:
      - image: cimg/base:stable
    steps:
      - add_ssh_keys:
          fingerprints:
            - "da:40:bb:6f:4b:bf:09:ca:a9:ed:e0:1a:95:22:c6:c7"
      - run: |
          git remote add production elmeri.digit.fi:digit_api.git
          git push production master
  
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build

